# Generated by Django 5.2.15 on 2026-07-07 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DetectedFace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bounding_box', models.JSONField()),
                ('face_confidence', models.FloatField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_faces', to='api.uploadedimage')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dominant_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('gender_confidence', models.FloatField(blank=True, null=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('emotion_confidence', models.FloatField(blank=True, null=True)),
                ('emotion_scores', models.JSONField(blank=True, null=True)),
                ('dominant_race', models.CharField(blank=True, max_length=50, null=True)),
                ('race_confidence', models.FloatField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('detected_face', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.detectedface')),
            ],
        ),
        migrations.CreateModel(
            name='KnownFace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('reference_image', models.ImageField(upload_to='known_faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_faces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_known', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('detected_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_logs', to='api.detectedface')),
                ('matched_face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to='api.knownface')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
