# Generated by Django 5.2.15 on 2026-07-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_uploadedimage_options_uploadedimage_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownface',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
