# Generated by Django 5.2.15 on 2026-07-07 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_knownface_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knownface',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='knownface',
            name='reference_image',
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='known_faces/')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('known_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='api.knownface')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
