# Generated by Django 5.2.15 on 2026-07-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_knownface_embedding_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceAnalysis',
        ),
    ]
