from enum import Enum


class Thresholds:
    FACE_DETECT_CONFIDENCE = 0.70
    FACE_MIN_SIZE_PX = 50

    SIMILARITY_THRESHOLD = 0.55
    CONFIDENCE_THRESHOLD = 45.0
    LIVE_MATCH_MARGIN = 0.05

    TRACK_EXPIRE_SECONDS = 3.0
    TRACK_MATCH_SCORE = 0.20
    TRACK_SMOOTHING = 0.50
    TRACK_IOU_RATIO = 0.60
    TRACK_CENTER_RATIO = 0.40

    FRONTAL_ASPECT_MIN = 0.65
    FRONTAL_ASPECT_MAX = 1.45

    RETINAFACE_MIN_CONFIDENCE = 0.90

    CLAHE_CLIP_LIMIT = 2.0
    CLAHE_TILE_SIZE = (8, 8)
    CLAHE_MAX_DIMENSION = 1000
